support for pytrees in projection_halfspace and projection_hyperplane
google/jaxopt pull request #47
Opened 2021-09-28 20:05 UTC by gowerrobert

1. re-implemented projection_halfspace and projection_hyperplane so they work with pytrees
2. added tests to reflect support
3. also added a test for projection_box,

2021-09-28 22:35 UTC, mblondel requested changes
Thanks a lot Robert!

I left some comments

2021-09-28 22:35 UTC, mblondel commented on jaxopt/_src/projection.py
> +                 the same structure as x ``b`` is a scalar.
```suggestion
                 the same structure as ``x`` and ``b`` is a scalar.
```

2021-09-28 22:35 UTC, mblondel commented on jaxopt/_src/projection.py
> +  scale = (tree_util.tree_vdot(a,x) -b)/tree_util.tree_vdot(a,a)
```suggestion
  scale = (tree_util.tree_vdot(a,x) -b) / tree_util.tree_vdot(a,a)
```

2021-09-28 22:35 UTC, mblondel commented on jaxopt/_src/projection.py
> +                 the same structure as x and ``b`` is a scalar.
```suggestion
                 the same structure as ``x`` and ``b`` is a scalar.
```

2021-09-28 22:35 UTC, mblondel commented on jaxopt/_src/projection.py
> +  scale = jax.nn.relu(tree_util.tree_vdot(a,x) -b)/tree_util.tree_vdot(a,a)
```suggestion
  scale = jax.nn.relu(tree_util.tree_vdot(a, x) - b) / tree_util.tree_vdot(a, a)
```

2021-09-28 22:35 UTC, mblondel commented on jaxopt/_src/projection.py
> +def _clip_safe(x, a, b):
```suggestion
def _clip_safe(x, lower, upper):
```

2021-09-28 22:35 UTC, mblondel commented on tests/projection_test.py
> +    # lower and upper are pytrees. Note: Does not work when U and L are scalars!
I think the following could potentially work:
```python
if isinstance(lower_bound, float):
  # If lower_bound is a scalar, create a pytree with the same structure as `x`
  lower_bound = tree_util.tree_zeros_like(x) + lower_bound
```
but let's do it in a separate PR.

2021-09-28 22:35 UTC, mblondel commented on tests/projection_test.py
> +    self.assertAllClose(tree_x, p)
Thanks for creating this test! I hadn't realized that we were missing it. 

Could you also check the case when `b` is small? A simple assertion is to just check that the solution is feasible. A more advanced assertion would be to check that the optimality conditions are satisfied.

2021-09-29 15:50 UTC, gowerrobert commented
Thanks for the suggestions and comments @mblondel  ! I've incorporated them all (except the further fix for box projections). Shall I squash the commits into one?

2021-09-29 18:05 UTC, mblondel commented
Yes please :)

Le mer. 29 sept. 2021 à 17:50, Robert M. Gower ***@***.***> a
écrit :

> Thanks for the suggestions and comments @mblondel
> <https://github.com/mblondel> ! I've incorporated them all (except the
> further fix for box projections). Shall I squash the commits into one?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/google/jaxopt/pull/47#issuecomment-930304697>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABZB2XDYZFPONGYG73256TUEMYTTANCNFSM5E6HBEYA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-29 18:20 UTC, gowerrobert commented
Ok, I think I managed to squash the commits (excluding a merge commit that came for free)

2021-09-29 18:42 UTC, mblondel commented
Did you force push? There are currently 8 commits.

2021-09-29 19:04 UTC, gowerrobert commented
nope, I hadn't forced the push. Now it's right (I hope)

2021-09-29 20:25 UTC, merged